version: '3.4'

services:
  gamingwebapp:
    image: ${DOCKER_REGISTRY}gamingwebapp
    build:
      context: .
      dockerfile: src/Applications/GamingWebApp/Dockerfile
    depends_on:
      - "leaderboard.webapi"

  leaderboard.webapi:
    image: ${DOCKER_REGISTRY}leaderboardwebapi
    build:
      context: .
      dockerfile: src/Services/Leaderboard.WebAPI/Dockerfile
    depends_on:
      - "sql.data"

  sql.data:
    image: mcr.microsoft.com/mssql/server
